config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :shoes, only: [:index, :shoe, :destroy, :show] do
    resources :check_ins, only: [:create]
  end
  resources :user_shoes, only: [:new, :create]

  authenticated :user do
    root 'shoes#index', as: 'authenticated_root'
  end

  root 'welcome#index'
end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
  belongs_to :user_shoe
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  belongs_to :shoe
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  has_many :user_shoes
  has_many :users, through: :user_shoes

  accepts_nested_attributes_for :user_shoes

  validates :brand, presence: true
  validates :model, presence: true
  validates :color, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_shoes
  has_many :shoes, through: :user_shoes
end

app/models/user_shoe.rb
class UserShoe < ActiveRecord::Base
  belongs_to :user
  belongs_to :shoe

  has_many :check_ins

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  def create
    @user_shoe_id = params[:shoe_id]
    @user_shoe = UserShoe.find(@user_shoe_id)
    @date = Date.today
    @check_in = CheckIn.new(user_shoe: @user_shoe, date: @date)
    if @check_in.save
      flash[:notice] = "Successfully Checked In"
      redirect_to root_path
    end
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  include ActionView::Helpers::DateHelper

  def index
    if !current_user.nil?
      @user = current_user
      @user_shoes = UserShoe.where(user: @user)
      @check_ins = CheckIn.where(user_shoe: @user_shoes)

      @sunday = Date.today.beginning_of_week(:sunday)
      @saturday = Date.today.end_of_week(:sunday)

      @last_week = (@sunday - 7..@saturday - 7).to_a
      @this_week = (@sunday..@saturday).to_a

      if !@check_ins.empty?
        @last_week_check_ins = @check_ins.where(
          date: @last_week).select("distinct on (date)*")
        @this_week_check_ins = @check_ins.where(
          date: @this_week).select("distinct on (date)*")

        @last_check_in = @check_ins.last.created_at
        @time_since_last_check_in = time_ago_in_words(
          @last_check_in, include_seconds: true).concat(" ago")

        @trending_user_shoe = @this_week_check_ins.group(
          'user_shoe_id').order('count(*) desc').limit(1).pluck(
            'user_shoe_id').first

        if !@trending_user_shoe.nil?
          @shoe_of_week = UserShoe.find(@trending_user_shoe)
        else
          @shoe_of_week = nil
        end
      end

    else
      @user_shoes = UserShoe.all
    end
  end

  def show
    @user = current_user
    @user_shoes = UserShoe.where(user: @user)
    @user_shoe = UserShoe.find(params[:id])
    @check_ins = CheckIn.where(user_shoe: @user_shoe)

    if !@check_ins.empty?
      @last_check_in = Date.parse(
        CheckIn.where(user_shoe: @user_shoe).last.date)
      @total_check_ins = CheckIn.where(user_shoe: @user_shoe).count
    else
      @last_check_in = nil
    end

    respond_to do |format|
      format.js
    end

  end

  def destroy
    @user_shoe = UserShoe.find(params[:id])
    @user = current_user
    if !current_user.nil? && !@user_shoe.nil?
      @user_shoe.destroy
      flash[:notice] = "Successfully Deleted"
      redirect_to root_path
    else
      @shoe = Shoe.find(params[:id]).destroy
      redirect_to root_path
    end
  end

  private

  def shoe_params
    params.require(:shoe).permit(:model, :brand, :color)
  end
end

app/controllers/user_shoes_controller.rb
class UserShoesController < ApplicationController
  def new
    if !current_user.nil?
      @user_shoe = UserShoe.new
      @shoe = Shoe.new
    else
      flash[:notice] = 'Must be signed in to add shoes'
      redirect_to root_path
    end
  end

  def create
    @user = current_user
    @shoe = Shoe.new(shoe_params)
    @image = params[:user_shoe][:image] unless params[:user_shoe].nil?
    @user_shoe = UserShoe.new(user: @user, shoe: @shoe, image: @image)
    if @shoe.save
      @user_shoe.save
      flash[:notice] = 'Successfully Added'
      redirect_to root_path
    else
      flash[:notice] = @shoe.errors.full_messages.join('. ')
      render :new
    end
  end

  private

  def shoe_params
    params.require(:shoe).permit(:model, :brand, :color)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/collections/index.html.erb
<h2>my collections index page</h2>
<%= link_to 'Add New Shoes', new_shoe_path %><br>

<% if !@shoes.empty? %>
  <table class="medium-8">
    <tr>
      <th>Model</th>
      <th>Brand</th>
      <th>Color</th>
    </tr>
    <%- @shoes.each do |shoe| -%>
      <tr>
        <td><%= shoe.model %></td>
        <td><%= shoe.brand %></td>
        <td><%= shoe.color %></td>
        <td><%= link_to 'edit', user_collection_path(shoe.users, shoe.collections.pluck(:id).first) %>
        <td><%= link_to 'delete', shoe_path(shoe), method: :delete %></td>
      </tr>
    <%- end -%>
  </table>
<%- end -%>

app/views/layouts/_flash.html.erb
<div id="notice_wrapper">
  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <p class="notice"><%= value %></p>
    </div>
  <%- end -%>
</div>

app/views/layouts/_tab_bar.html.erb
<nav class="tab-bar">
  <%- if !current_user.nil? -%>
    <section class="left-small">
      <a class="left-off-canvas-toggle menu-icon"><span></span></a>
    </section>
  <%- end -%>
  <section class="show-for-portrait middle tab-bar-section">
    <h1 class="title">Shoe Game</h1>
  </section>
</nav>

<aside class="left-off-canvas-menu">
  <ul class="off-canvas-list">
    <li>
      <label>My Shoe Collection</label>
    </li>

    <%- if current_user -%>
      <li><%= link_to current_user.email, root_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>

      <%- if !@user_shoes.nil? -%>
        <%- @user_shoes.each do |user_shoe| -%>
          <%= link_to shoe_path(user_shoe), remote: true do %>
            <%= image_tag(user_shoe.image_url(:list)) %>
          <%- end -%>
        <%- end -%>
      <%- end -%>

    <%- else -%>
      <li><a href="/">Home</a></li>
      <li><a href="/users/sign_in">Sign in to see the goodies</a></li>
    <%- end -%>
  </ul>
</aside>

app/views/layouts/_top_bar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
       <h1></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li><%= link_to 'Shoe Game', root_path %></a>
      </li>
    </ul>
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to current_user.email, root_path %></li>
        <li><%= link_to 'Sign Out!', destroy_user_session_path, method: :delete %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shoe Game</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/flash" %>

  <section class="navigation-section fixed">
    <div class="row max-width show-for-large-up">
      <div class="zero-padding large-12 columns">

        <%= render "layouts/top_bar" %>

      </div>
    </div>
  </section>

  <div class="off-canvas-wrap" data-offcanvas>
    <div class="fixed off-canvas-fixed hide-for-large-up"><a class="exit-off-canvas"></a>
      <%= render "layouts/tab_bar" %>
    </div>

    <div class="inner-wrap"><a class="exit-off-canvas"></a>
      <section class="main-section">
        <div class="row max-width">
          <div class="zero-padding large-12 columns">

            <%= yield %>

          </div>
        </div>
      </section>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/shoes/_calendar.html.erb
<div id="calendar">
  <div class="calendar_content">
    <%- if !@check_ins.empty? -%>
      <Table align="center">
        <tr>
          <td><p>S</p></td>
          <td><p>M</p></td>
          <td><p>T</p></td>
          <td><p>W</p></td>
          <td><p>T</p></td>
          <td><p>F</p></td>
          <td><p>S</p></td>
        </tr>
        <tr>
          <% @last_week.each do |day| %>
            <td>
              <p>
                <%#= day %>
                <% @last_week_check_ins.each do |check_in| %>
                  <% if check_in.date == day.strftime("%Y-%m-%d") %>
                    <%= image_tag(check_in.user_shoe.image_url(:calendar)) %>
                  <%- end -%>
                <%- end -%>
              </p>
            </td>
          <%- end -%>
        </tr>
        <tr>
          <% @this_week.each do |day| %>
            <td>
              <p>
                <%#= day %>
                <% @this_week_check_ins.each do |check_in| %>

                  <% if check_in.date == day.strftime("%Y-%m-%d") %>
                    <%= image_tag(check_in.user_shoe.image_url(:calendar)) %>
                  <%- end -%>
                <%- end -%>
              </p>
            </td>
          <%- end -%>
        </tr>
      </table>
    <%- end -%>
  </div>
</div>

app/views/shoes/_show.html.erb
<div id="test2" class="text-center hide-for-large-up"><br>
  <%= image_tag(@user_shoe.image_url(:thumb)) %>
    <table class="full-width">
      <tr>
        <th>Model</th>
        <th>Brand</th>
        <th>Color</th>
      </tr>
      <tr>
        <td><%= @user_shoe.shoe.model %></td>
        <td><%= @user_shoe.shoe.brand %></td>
        <td><%= @user_shoe.shoe.color %></td>
      </tr>
    </table>
    <div>
      <%- if !@last_check_in.nil? -%>
        <h3>Last worn: <%= @last_check_in.strftime("%A, %B %d, %Y") %></h3>
        <h3>Total wear count: <%= @total_check_ins %></h3><br>
      <%- end -%>
    </div>
  <%= link_to '<button>check in</button>'.html_safe, shoe_check_ins_path(@user_shoe), method: :post %><br>
  <%= link_to '<button>delete</button>'.html_safe, shoe_path(@user_shoe), method: :delete %>
</div>

app/views/shoes/index.html.erb
<%- if !current_user.nil? -%>
  <div class='text-center'>
    <h2>My Shoes</h2>
    <%= link_to '<button>Add New Shoes</button>'.html_safe, new_user_shoe_path %><br>
    <%= render 'calendar' %>
  </div>

  <div class="row show-for-large-up">
    <%- if !@user_shoes.empty? -%>
      <div class="small-12 small-centered columns">
        <table>
          <tr>
            <th class="small-4">Image</th>
            <th class="small-1">Total Check-ins</th>
            <th class="small-1">Last Check-in</th>

          </tr>
          <%- @user_shoes.each do |user_shoe| -%>
            <tr id="shoe row">
              <td><%= image_tag(user_shoe.image_url(:small)) if user_shoe.image? %>
              <%= link_to '<button>check in</button>'.html_safe, shoe_check_ins_path(user_shoe), method: :post %>
              <%= link_to '<button>delete</button>'.html_safe, shoe_path(user_shoe), method: :delete %><br>
              <%= user_shoe.shoe.model %>
              <%= user_shoe.shoe.brand %>
              <%= user_shoe.shoe.color %></td>
              <td><%= user_shoe.check_ins.size %></td>
              <td><%= user_shoe.check_ins.pluck(:date).last %></td>
            </tr>
          <%- end -%>
        </table>
      </div>
    <%- end -%>
  </div>

  <div id="test1">
    <div id="row-margin-zero" class="row hide-for-large-up" data-equalizer="top">
      <div id="column-padding-zero" class="small-6 medium-6 columns">
        <div id="panel-clean" class="panel" data-equalizer-watch="top">

          <div class="dashboard">
            <h1>Shoe Count</h1>
            <p><%= @user_shoes.all.size %></p>
          </div>

        </div>
      </div>
      <div id="column-padding-zero" class="small-6 medium-6 columns">
        <div id="panel-clean" class="panel" data-equalizer-watch="top">

          <div class="dashboard">
            <h1>Check-ins this week</h1>
            <%- if !@check_ins.empty? -%>
              <p>
                <%= @this_week_check_ins.size %>
              </p>
            <%- else -%>
              <p>0</p>
            <%- end -%>
          </div>

        </div>
      </div>
    </div>
    <div id="row-margin-zero" class="row hide-for-large-up" data-equalizer="bottom">
      <div id="column-padding-zero" class="small-6 medium-6 columns">
        <div id="panel-clean" class="panel" data-equalizer-watch="bottom">

          <div class="dashboard">
            <h1>Shoe of the Week</h1>
            <%- if !@shoe_of_week.nil? -%>
              <p><%= image_tag(@shoe_of_week.image_url(:small)) %></p>
            <%- else -%>
              <div class="wordy">
                <p>No check ins this week</p>
              </div>
            <%- end -%>
          </div>

        </div>
      </div>

      <div id="column-padding-zero" class="small-6 medium-6 columns">
        <div id="panel-clean" class="panel" data-equalizer-watch="bottom">

          <div class="dashboard">
            <h1>Last check-in</h1>
            <div class="wordy">
              <%- if !@check_ins.empty? -%>

                <p>  <%= @time_since_last_check_in %> </p>

              <%- else -%>
                <p>
                  No check ins
                </p>
              <%- end -%>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

<%- else -%>
  <h2>Welcome to Shoe Tracker</h2>
<%- end -%>

app/views/shoes/show.html.erb
<%#= link_to 'back to my shoes', root_path -%><br>
<%#= image_tag(@user_shoe.image_url(:small)) %>
<table>
  <tr>
    <th>Model</th>
    <th>Brand</th>
    <th>Color</th>
  </tr>
  <tr>
    <td><%= @user_shoe.shoe.model %></td>
    <td><%= @user_shoe.shoe.brand %></td>
    <td><%= @user_shoe.shoe.color %></td>
  </tr>
</table>

app/views/shoes/show.js.erb
$('#test2').remove();
$('#test1').hide().after('<%= j render("show") %>');
console.log("<%= @user_shoe.shoe.model %>");

app/views/user_shoes/new.html.erb
<div id="row-margin-zero" class="row">
  <div class="small-10 medium-4 large-3 small-centered columns text-center">
    <%= form_for @user_shoe do |f| %>
      <%= fields_for @shoe do |ff| %>
        <%= ff.label :model %>
        <%= ff.text_field :model %>
        <%= ff.label :brand %>
        <%= ff.text_field :brand %>
        <%= ff.label :color %>
        <%= ff.text_field :color %>
      <% end %>

      <%= f.file_field :image %>
      <%= f.submit 'Submit', class: "button round" %>
    <%- end -%>
  </div>
</div>

app/views/welcome/index.html.erb
<div id='banner'>
  <div class='banner_content'>
    <h1>Shoe Game</h1>
    <p>The Shoe Collection Tracking App</p>

    <%= link_to '<button>Sign In</button>'.html_safe, new_user_session_path %><br>
    <%= link_to '<button>Sign Up</button>'.html_safe, new_user_registration_path %>

  </div>
</div>